/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.librairy.service.graph.facade.model;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Format { 
  CSV, JSONL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Format\",\"namespace\":\"org.librairy.service.graph.facade.model\",\"symbols\":[\"CSV\",\"JSONL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
