/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.librairy.service.graph.facade.model;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class GraphInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GraphInfo\",\"namespace\":\"org.librairy.service.graph.facade.model\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"description\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null,\"order\":\"ignore\"},{\"name\":\"date\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null,\"order\":\"ignore\"},{\"name\":\"url\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null,\"order\":\"ignore\"},{\"name\":\"format\",\"type\":{\"type\":\"enum\",\"name\":\"Format\",\"symbols\":[\"CSV\",\"JSONL\"]}},{\"name\":\"nodes\",\"type\":{\"type\":\"record\",\"name\":\"Selection\",\"fields\":[{\"name\":\"query\",\"type\":{\"type\":\"record\",\"name\":\"Query\",\"fields\":[{\"name\":\"type\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"filter\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null,\"order\":\"ignore\"},{\"name\":\"fields\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},\"default\":[],\"order\":\"ignore\"}]}},{\"name\":\"count\",\"type\":\"long\",\"default\":0,\"order\":\"ignore\"}]},\"order\":\"ignore\"},{\"name\":\"edges\",\"type\":\"Selection\",\"order\":\"ignore\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
   private java.lang.String id;
   private java.lang.String description;
   private java.lang.String date;
   private java.lang.String url;
   private org.librairy.service.graph.facade.model.Format format;
   private org.librairy.service.graph.facade.model.Selection nodes;
   private org.librairy.service.graph.facade.model.Selection edges;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public GraphInfo() {}

  /**
   * All-args constructor.
   */
  public GraphInfo(java.lang.String id, java.lang.String description, java.lang.String date, java.lang.String url, org.librairy.service.graph.facade.model.Format format, org.librairy.service.graph.facade.model.Selection nodes, org.librairy.service.graph.facade.model.Selection edges) {
    this.id = id;
    this.description = description;
    this.date = date;
    this.url = url;
    this.format = format;
    this.nodes = nodes;
    this.edges = edges;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return description;
    case 2: return date;
    case 3: return url;
    case 4: return format;
    case 5: return nodes;
    case 6: return edges;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.String)value$; break;
    case 1: description = (java.lang.String)value$; break;
    case 2: date = (java.lang.String)value$; break;
    case 3: url = (java.lang.String)value$; break;
    case 4: format = (org.librairy.service.graph.facade.model.Format)value$; break;
    case 5: nodes = (org.librairy.service.graph.facade.model.Selection)value$; break;
    case 6: edges = (org.librairy.service.graph.facade.model.Selection)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'description' field.
   */
  public java.lang.String getDescription() {
    return description;
  }

  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.String value) {
    this.description = value;
  }

  /**
   * Gets the value of the 'date' field.
   */
  public java.lang.String getDate() {
    return date;
  }

  /**
   * Sets the value of the 'date' field.
   * @param value the value to set.
   */
  public void setDate(java.lang.String value) {
    this.date = value;
  }

  /**
   * Gets the value of the 'url' field.
   */
  public java.lang.String getUrl() {
    return url;
  }

  /**
   * Sets the value of the 'url' field.
   * @param value the value to set.
   */
  public void setUrl(java.lang.String value) {
    this.url = value;
  }

  /**
   * Gets the value of the 'format' field.
   */
  public org.librairy.service.graph.facade.model.Format getFormat() {
    return format;
  }

  /**
   * Sets the value of the 'format' field.
   * @param value the value to set.
   */
  public void setFormat(org.librairy.service.graph.facade.model.Format value) {
    this.format = value;
  }

  /**
   * Gets the value of the 'nodes' field.
   */
  public org.librairy.service.graph.facade.model.Selection getNodes() {
    return nodes;
  }

  /**
   * Sets the value of the 'nodes' field.
   * @param value the value to set.
   */
  public void setNodes(org.librairy.service.graph.facade.model.Selection value) {
    this.nodes = value;
  }

  /**
   * Gets the value of the 'edges' field.
   */
  public org.librairy.service.graph.facade.model.Selection getEdges() {
    return edges;
  }

  /**
   * Sets the value of the 'edges' field.
   * @param value the value to set.
   */
  public void setEdges(org.librairy.service.graph.facade.model.Selection value) {
    this.edges = value;
  }

  /** Creates a new GraphInfo RecordBuilder */
  public static org.librairy.service.graph.facade.model.GraphInfo.Builder newBuilder() {
    return new org.librairy.service.graph.facade.model.GraphInfo.Builder();
  }
  
  /** Creates a new GraphInfo RecordBuilder by copying an existing Builder */
  public static org.librairy.service.graph.facade.model.GraphInfo.Builder newBuilder(org.librairy.service.graph.facade.model.GraphInfo.Builder other) {
    return new org.librairy.service.graph.facade.model.GraphInfo.Builder(other);
  }
  
  /** Creates a new GraphInfo RecordBuilder by copying an existing GraphInfo instance */
  public static org.librairy.service.graph.facade.model.GraphInfo.Builder newBuilder(org.librairy.service.graph.facade.model.GraphInfo other) {
    return new org.librairy.service.graph.facade.model.GraphInfo.Builder(other);
  }
  
  /**
   * RecordBuilder for GraphInfo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GraphInfo>
    implements org.apache.avro.data.RecordBuilder<GraphInfo> {

    private java.lang.String id;
    private java.lang.String description;
    private java.lang.String date;
    private java.lang.String url;
    private org.librairy.service.graph.facade.model.Format format;
    private org.librairy.service.graph.facade.model.Selection nodes;
    private org.librairy.service.graph.facade.model.Selection edges;

    /** Creates a new Builder */
    private Builder() {
      super(org.librairy.service.graph.facade.model.GraphInfo.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.librairy.service.graph.facade.model.GraphInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.description)) {
        this.description = data().deepCopy(fields()[1].schema(), other.description);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.date)) {
        this.date = data().deepCopy(fields()[2].schema(), other.date);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.url)) {
        this.url = data().deepCopy(fields()[3].schema(), other.url);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.format)) {
        this.format = data().deepCopy(fields()[4].schema(), other.format);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.nodes)) {
        this.nodes = data().deepCopy(fields()[5].schema(), other.nodes);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.edges)) {
        this.edges = data().deepCopy(fields()[6].schema(), other.edges);
        fieldSetFlags()[6] = true;
      }
    }
    
    /** Creates a Builder by copying an existing GraphInfo instance */
    private Builder(org.librairy.service.graph.facade.model.GraphInfo other) {
            super(org.librairy.service.graph.facade.model.GraphInfo.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.description)) {
        this.description = data().deepCopy(fields()[1].schema(), other.description);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.date)) {
        this.date = data().deepCopy(fields()[2].schema(), other.date);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.url)) {
        this.url = data().deepCopy(fields()[3].schema(), other.url);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.format)) {
        this.format = data().deepCopy(fields()[4].schema(), other.format);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.nodes)) {
        this.nodes = data().deepCopy(fields()[5].schema(), other.nodes);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.edges)) {
        this.edges = data().deepCopy(fields()[6].schema(), other.edges);
        fieldSetFlags()[6] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.String getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public org.librairy.service.graph.facade.model.GraphInfo.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public org.librairy.service.graph.facade.model.GraphInfo.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'description' field */
    public java.lang.String getDescription() {
      return description;
    }
    
    /** Sets the value of the 'description' field */
    public org.librairy.service.graph.facade.model.GraphInfo.Builder setDescription(java.lang.String value) {
      validate(fields()[1], value);
      this.description = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'description' field has been set */
    public boolean hasDescription() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'description' field */
    public org.librairy.service.graph.facade.model.GraphInfo.Builder clearDescription() {
      description = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'date' field */
    public java.lang.String getDate() {
      return date;
    }
    
    /** Sets the value of the 'date' field */
    public org.librairy.service.graph.facade.model.GraphInfo.Builder setDate(java.lang.String value) {
      validate(fields()[2], value);
      this.date = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'date' field has been set */
    public boolean hasDate() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'date' field */
    public org.librairy.service.graph.facade.model.GraphInfo.Builder clearDate() {
      date = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'url' field */
    public java.lang.String getUrl() {
      return url;
    }
    
    /** Sets the value of the 'url' field */
    public org.librairy.service.graph.facade.model.GraphInfo.Builder setUrl(java.lang.String value) {
      validate(fields()[3], value);
      this.url = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'url' field has been set */
    public boolean hasUrl() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'url' field */
    public org.librairy.service.graph.facade.model.GraphInfo.Builder clearUrl() {
      url = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'format' field */
    public org.librairy.service.graph.facade.model.Format getFormat() {
      return format;
    }
    
    /** Sets the value of the 'format' field */
    public org.librairy.service.graph.facade.model.GraphInfo.Builder setFormat(org.librairy.service.graph.facade.model.Format value) {
      validate(fields()[4], value);
      this.format = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'format' field has been set */
    public boolean hasFormat() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'format' field */
    public org.librairy.service.graph.facade.model.GraphInfo.Builder clearFormat() {
      format = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'nodes' field */
    public org.librairy.service.graph.facade.model.Selection getNodes() {
      return nodes;
    }
    
    /** Sets the value of the 'nodes' field */
    public org.librairy.service.graph.facade.model.GraphInfo.Builder setNodes(org.librairy.service.graph.facade.model.Selection value) {
      validate(fields()[5], value);
      this.nodes = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'nodes' field has been set */
    public boolean hasNodes() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'nodes' field */
    public org.librairy.service.graph.facade.model.GraphInfo.Builder clearNodes() {
      nodes = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'edges' field */
    public org.librairy.service.graph.facade.model.Selection getEdges() {
      return edges;
    }
    
    /** Sets the value of the 'edges' field */
    public org.librairy.service.graph.facade.model.GraphInfo.Builder setEdges(org.librairy.service.graph.facade.model.Selection value) {
      validate(fields()[6], value);
      this.edges = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'edges' field has been set */
    public boolean hasEdges() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'edges' field */
    public org.librairy.service.graph.facade.model.GraphInfo.Builder clearEdges() {
      edges = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    public GraphInfo build() {
      try {
        GraphInfo record = new GraphInfo();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.description = fieldSetFlags()[1] ? this.description : (java.lang.String) defaultValue(fields()[1]);
        record.date = fieldSetFlags()[2] ? this.date : (java.lang.String) defaultValue(fields()[2]);
        record.url = fieldSetFlags()[3] ? this.url : (java.lang.String) defaultValue(fields()[3]);
        record.format = fieldSetFlags()[4] ? this.format : (org.librairy.service.graph.facade.model.Format) defaultValue(fields()[4]);
        record.nodes = fieldSetFlags()[5] ? this.nodes : (org.librairy.service.graph.facade.model.Selection) defaultValue(fields()[5]);
        record.edges = fieldSetFlags()[6] ? this.edges : (org.librairy.service.graph.facade.model.Selection) defaultValue(fields()[6]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
